var annotated_dup =
[
    [ "Admin", "class_admin.html", null ],
    [ "AdminManager", "class_admin_manager.html", null ],
    [ "AuthManager", "class_auth_manager.html", null ],
    [ "AuthSystem", "class_auth_system.html", null ],
    [ "Cart", "class_cart.html", null ],
    [ "ChatManager", "class_chat_manager.html", null ],
    [ "ChatMessage", "class_chat_message.html", null ],
    [ "Command", "class_command.html", null ],
    [ "Customer", "class_customer.html", null ],
    [ "CustomerManager", "class_customer_manager.html", null ],
    [ "DatabaseManager", "class_database_manager.html", null ],
    [ "Invoker", "class_invoker.html", null ],
    [ "Logger", "class_logger.html", null ],
    [ "MenuItem", "class_menu_item.html", null ],
    [ "MenuManager", "class_menu_manager.html", null ],
    [ "NetworkManager", "class_network_manager.html", null ],
    [ "Observer", "class_observer.html", null ],
    [ "Order", "class_order.html", null ],
    [ "OrderCommand", "class_order_command.html", null ],
    [ "OrderManager", "class_order_manager.html", null ],
    [ "OrderStatus", "class_order_status.html", null ],
    [ "OrderStatusObserver", "class_order_status_observer.html", null ],
    [ "Restaurant", "class_restaurant.html", null ],
    [ "RestaurantManager", "class_restaurant_manager.html", null ],
    [ "RestaurantOwner", "class_restaurant_owner.html", null ],
    [ "RestaurantOwnerManager", "class_restaurant_owner_manager.html", null ],
    [ "SecurityUtils", "class_security_utils.html", null ],
    [ "Server", "class_server.html", null ],
    [ "Session", "struct_session.html", null ],
    [ "User", "class_user.html", null ],
    [ "WebSocketServer", "class_web_socket_server.html", null ]
];